export const FILTER_ACTIONS =  {
    FILTER_ALL: 'FILTER_ALL',
    FILTER_MERCHANT: 'FILTER_MERCHANT',
    FILTER_STATUS: 'FILTER_STATUS',
    FILTER_DATE: 'FILTER_DATE',
    FILTER_MIN_MAX: 'FILTER_MIN_MAX',
    CLEAR_FILTER: 'CLEAR_FILTER',
}