export const FILTER_ACTIONS =  {
    FILTER_ALL: 'FILTER_ALL',
    FILTER_MERCHANT: 'FILTER_MERCHANT',
    FILTER_STATUS: 'FILTER_STATUS',
    FILTER_FROM_DATE:'FILTER_FROM_DATE',
    FILTER_TO_DATE: 'FILTER_TO_DATE',
    FILTER_MIN: 'FILTER_MIN',
    FILTER_MAX: 'FILTER_MAX',
    CLEAR_FILTER: 'CLEAR_FILTER',
}